### PR TITLE
updated setup guide in readme + enabled okawo's lens undistort stuff

### PR DESCRIPTION
**Pull request by djblazkowicz**
added some clarity on how to set it up with non-relativty boards and expanded and some guidance on features that can be adjusted in the settings file

### CODE REVIEW

**Comment by okawo80085** [comment]
maybe you should also mention that if you change the config after you installed the driver, you don't need reinstall the driver?
in the readme
after or before the installation steps

**Comment by okawo80085** [comment]
also increment the driver version

**Comment by okawo80085** [comment]
oh and prob move the aforementioned version into macro or smthing

**Comment by thelostgarden** [comment]
Thank you ! 😄

**Pull request merged**
